### ISSUE TITLE
GAndY

### ISSUE THREAD

**Issue by BroWo1** [Humanoid-a/gpeclubwebsite#1]
Why andy is gay?

**Comment by JeffreyWang08** [comment]
because Andy is idiot

**Comment by Humanoid-a** [comment]
sb

________________________________
发件人: JeffreyWang08 ***@***.***>
发送时间: 2024年12月30日 10:27
收件人: Humanoid-a/gpeclubwebsite ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [Humanoid-a/gpeclubwebsite] GAndY (Issue #1)


Closed #1<https://github.com/Humanoid-a/gpeclubwebsite/issues/1> as completed.

―
